### PR TITLE
[⚠Work In Progress] Better aiming system 🎯

### PR DESCRIPTION
**Pull request by Hedgefog**
The idea is to make the bot's aim more realistic. 

The current implementation is too twitchy and bots almost never miss, it's not really cool for a server where bots are just a temporary replacement for players. So, I think some discussion is needed here.

I've added some configurable aim error from podbot implementation. Also added some additional checks if the enemy is in sight before aiming, to remove useless aiming and make it more realistic using gradual adjustment.

### CODE REVIEW

**Comment by XuberAxel** [comment]
I think the title says it all, but I'll explain why I need the bots to have a accuracy rate. Apparently the bots are semi-gods or something similar because no matter how easy they are, they still manage to hit their target with all the bullets and it seems very unfair to people. I'm supposed to put bots on my server to attract people but when they see the bots kill them with 4 shots in a row from any distance, they get bored and leave. That's not counting how fake they are when they shoot you in the head. I want to put some bots that are not idiots but that do not hit all the bullets either. It would be great if you could add something called "accuracy" to the difficulty setting that would indicate how likely the bot is to target the player's hitbox. The less likely it is, the crosshair will gently wobble from side to side as if the bot is drunk. 100 would be a perfect probability (like right now) and 0 would be as bad as someone with no hands. It is a suggestion that it would be good if they did. Thank you very much for your work and keep it up! :D

**Comment by XuberAxel** [comment]
Please add these new features. I need the error aiming. If you add this, the YaPB will be the most used bot plugin....

**Comment by kam92** [comment]
I tweaked the bots and they are now way better:

in difficulty.cfg:
Noob = 0.4, 0.5, 1, 2, 2
Easy = 0.4, 0.5, 3, 5, 2
Normal = 0.3, 0.5, 15, 25, 15
Hard = 0.22, 0.4, 20, 76, 15
Expert = 0.2, 0.4, 25, 76, 15

honestly, 25% head-shot chance still huge, but manageable.


in yapb.cfg:
yb_camping_time_min "7.0"
yb_camping_time_max "12.0"

yb_tkpunish "0" < this stops the bot from staring at the player when shot by accident (bot will do this even if there is enemy in the screen so better make it ignore friendly fire)

yb_object_pickup_radius "1024.0"

yb_shoots_thru_walls "0" < this is huge, the shot thru walls makes bots walk like they are with lag, is bugged, this was the biggest change for me. bots just walk normally now and stop aiming at walls and doing weird things based on audio. 

yb_think_fps "90.0" < don't know if there is any difference, but didn't harm for sure

yb_join_delay "0.0"

yb_difficulty "3"

yb_difficulty_min "0"
yb_difficulty_max "4"
these 2 will make bots generate between noob and expert, so teams will always be kinda mixed.

yb_difficulty_auto "0"


And I also tweaked weapon.cfg, for me it didn't make sense to change AK for m4, and sniper bot will be more economic to focus only on awp, buying subs and deagle only untill then. but that is not about difficulty and only my personal preference.

**Comment by jeefo** [comment]
Assumes it's dead by now. Incorporated current changes into master branch.

Thank you. Closed.

**Pull request closed without merging**
