### PR TITLE
control: text changes in the control menu. replaced "waypoint" with "node"

### PR DESCRIPTION
**Pull request by commandcobra7**

### CODE REVIEW

**Comment by jeefo** [comment]
I'm agree with that. But, you need to update [original] section of language files as well.

**Comment by commandcobra7** [comment]
> I'm agree with that. But, you need to update [original] section of language files as well.

is it ok now

**Comment by Vladislav4KZ** [comment]
If you're going to correct the text in the menu, why capitalize all the words in the menu items? It's not like they're titles.

**Comment by commandcobra7** [comment]
If the pull request is to be approved, let it be approved, otherwise I will delete the pull request.

**Comment by commandcobra7** [comment]
> If you're going to correct the text in the menu, why capitalize all the words in the menu items? It's not like they're titles.

It's not the title anyway, I just didn't change the "waypoint" text in the menu. Bots were trying to change magazines while the shield was active, I fixed this and made some changes to the goal filters.

**Comment by Vladislav4KZ** [comment]
> It's not the title anyway, I just didn't change the \"waypoint\" text in the menu.

I meant this:
```
 \yBots Weapon Mode\w 
 
 1. Knives Only 
 2. Pistols Only 
 3. Shotguns Only 
 4. Machine Guns Only 
 5. Rifles Only 
 6. Sniper Weapons Only 
 7. All Weapons 


0. Exit
```

In menu items 1 to 7, you wrote the word "Only" with a capital letter. The same applies to other menu items, where each word begins with a capital letter.

**Comment by commandcobra7** [comment]
> > It's not the title anyway, I just didn't change the "waypoint" text in the menu.
> 
> I meant this:
> 
> ```
> \yBots Weapon Mode\w 
>  
> 1. Knives Only 
> 2. Pistols Only 
> 3. Shotguns Only 
> 4. Machine Guns Only 
> 5. Rifles Only 
> 6. Sniper Weapons Only 
> 7. All Weapons 
> 
> 
> 0. Exit
> ```
> 
> In menu items 1 to 7, you wrote the words "Only", "Weapons" and "Guns" with a capital letter. The same applies to other menu items, where each word begins with a capital letter.

is it okay now

**Comment by commandcobra7** [comment]
@Vladislav4KZ is it okay now

**Review by jeefo — APPROVED** [review]

**Comment by Vladislav4KZ** [comment]
@commandcobra7 please, read the comments in the review. There, under specific lines of code, I wrote what needs to be fixed.

**Comment by commandcobra7** [comment]
> @commandcobra7 please, read the comments in the review. There, under specific lines of code, I wrote what needs to be fixed.

I corrected it again, the capital initials were already there, so I restored them to their original state.

**Comment by commandcobra7** [comment]
> > I corrected it again, the capital initials were already there, so I restored them to their original state.
> 
> @commandcobra7 Don't you see 8 pending review comments?

I already did what you said

**Comment by Vladislav4KZ** [comment]
@commandcobra7

**Comment by commandcobra7** [comment]
What, do you want me to change it from "node" to "waypoint"?

**Comment by Vladislav4KZ** [comment]
> What, do you want me to change it from "node" to "waypoint"?

See the screenshot

**Comment by commandcobra7** [comment]
> > What, do you want me to change it from "node" to "waypoint"?
> 
> See the screenshot

Ok I understand, I will change it to "graph"

**Comment by commandcobra7** [comment]
ok i edited it again

**Review by Vladislav4KZ — APPROVED** [review]

**Comment by commandcobra7** [comment]
Did it happen this time?

**Comment by Vladislav4KZ** [comment]
I've approved the changes and marked all comments as resolved.

**Review by Vladislav4KZ — APPROVED** [review]

**Comment by jeefo** [comment]
Thank you @commandcobra7 & @Vladislav4KZ

**Pull request merged**
